# Generated by Django 3.2.7 on 2021-10-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('telegram_akkount', models.CharField(max_length=300, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('about_car', models.CharField(blank=True, max_length=1000, null=True)),
                ('departure_station', models.CharField(max_length=200)),
                ('arrival_station', models.CharField(max_length=200)),
                ('departure_time', models.DateTimeField(null=True)),
                ('number_of_vacancies', models.IntegerField(default=1)),
                ('sex', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default='Erkak', max_length=50)),
                ('price', models.CharField(max_length=200)),
                ('car_picture', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, default='000000', max_length=6)),
                ('edited_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('longitude', models.CharField(max_length=40, null=True)),
                ('latitude', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=13)),
                ('tg_akkount', models.CharField(max_length=30, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('user_status', models.CharField(choices=[('Tasdiqlanmagan', 'Tasdiqlanmagan'), ('Tasdiqlangan', 'Tasdiqlangan')], default='Tasdiqlangan', max_length=40)),
            ],
        ),
    ]
