# Generated by Django 3.2.8 on 2021-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211005_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_station',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_station',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sex',
            field=models.CharField(choices=[('Ayol', 'Ayol'), ('Erkak', 'Erkak'), ('Ixtiyoriy', 'Ixtiyoriy')], default='Ixtiyoriy', max_length=50),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='tg_akkount',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user_status',
            field=models.CharField(choices=[('Tasdiqlangan', 'Tasdiqlangan'), ('Tasdiqlanmagan', 'Tasdiqlanmagan')], default='Tasdiqlanmagan', max_length=40),
        ),
    ]
